NAME = $(shell grep -m1 NAME $(firstword $(INFO)) | cut -d\= -f2)
DESCRIPTION = $(shell grep -m1 DESCRIPTION $(firstword $(INFO)) | cut -d\= -f2)
PKGNAME = $(shell grep -m1 PKGNAME $(firstword $(INFO)) | cut -d\= -f2)
VERSION = $(shell grep -m1 VERSION $(firstword $(INFO)) | cut -d\= -f2)
AUTHOR = $(shell grep -m1 AUTHOR $(firstword $(INFO)) | cut -d\= -f2)
MAIL := $(shell grep -m1 MAIL $(firstword $(INFO)) | cut -d\= -f2 | tr '[A-Za-z]' '[N-ZA-Mn-za-m]')
URL = $(shell grep -m1 URL $(firstword $(INFO)) | cut -d\= -f2)
SOURCE = $(shell grep -m1 URL $(firstword $(SOURCE)) | cut -d\= -f2)
LICENSE = $(shell grep -m1 LICENSE $(firstword $(INFO)) | cut -d\= -f2)
EXECUTABLE = $(PKGNAME)
PKGDESCRIPTION = $(DESCRIPTION)
